Controllers/UserAuthController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SpringOceanTechnologiesIMS.Data;
using SpringOceanTechnologiesIMS.Models;
using SpringOceanTechnologiesIMS.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace SpringOceanTechnologiesIMS.Controllers
{
    public class UserAuthController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;

        public UserAuthController(ApplicationDbContext context,
                                  UserManager<ApplicationUser> userManager,
                                  SignInManager<ApplicationUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            loginModel.LoginInValid = "true";

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(loginModel.Email,
                                                                     loginModel.Password,
                                                                     loginModel.RememberMe,
                                                                     lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    loginModel.LoginInValid = "";
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt");
                }

            }
            return PartialView("_UserLoginPartial", loginModel);

        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();

            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterUser(RegistrationModel registrationModel)
        {
            registrationModel.RegistrationInValid = "true";

            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser
                {
                    UserName = registrationModel.Email,
                    Email = registrationModel.Email,
                    PhoneNumber = registrationModel.PhoneNumber,
                    FirstName = registrationModel.FirstName,
                    LastName = registrationModel.LastName,
                    Address1 = registrationModel.Address1,
                    Address2 = registrationModel.Address2,
                    PostCode = registrationModel.PostCode

                };

                var result = await _userManager.CreateAsync(user, registrationModel.Password);

                if (result.Succeeded)
                {
                    registrationModel.RegistrationInValid = "";

                    await _signInManager.SignInAsync(user, isPersistent: false);

                    if (registrationModel.ProgrammeId != 0)
                    {
                        await AddProgrammeToUser(user.Id, registrationModel.ProgrammeId);

                    }

                    return PartialView("_UserRegistrationPartial", registrationModel);
                }

                AddErrorsToModelState(result);

            }
            return PartialView("_UserRegistrationPartial", registrationModel);

        }

        [AllowAnonymous]
        public async Task<bool> UserNameExists(string userName)
        {
            bool userNameExists = await _context.Users.AnyAsync(u => u.UserName.ToUpper() == userName.ToUpper());

            if (userNameExists)
                return true;

            return false;

        }

        private void AddErrorsToModelState(IdentityResult result)
        {
            foreach (var error in result.Errors)
                ModelState.AddModelError(string.Empty, error.Description);
        }

        private async Task AddProgrammeToUser(string userId, int programmeId)
        {
            UserProgramme userProgramme = new UserProgramme();
            userProgramme.ProgrammeId = programmeId;
            userProgramme.UserId = userId;
            _context.UserProgramme.Add(userProgramme);
            await _context.SaveChangesAsync();
        }
    }

}

Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore
@using SpringOceanTechnologiesIMS.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result, "admin"))
{
    <li class="nav-item dropdown show">
        <a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown">Admin</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Users</a>
            <a class="dropdown-item" asp-area="Admin" asp-controller="Centre" asp-action="Index">Centres</a>
            <a class="dropdown-item" asp-area="Admin" asp-controller="Programme" asp-action="Index">Programmes</a>
            <a class="dropdown-item" asp-area="Admin" asp-controller="UsersToProgramme" asp-action="Index">Users to Programmes</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-area="Admin" asp-controller="MediaType" asp-action="Index">MediaTypes</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">User to Centres</a>
            <a class="dropdown-item" href="#">Centres to programmes</a>


        </div>
    </li>
}
else if (!SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" href="#Courses"><i class="fas fa-laptop-code mr-1 text-info"></i>Courses</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#ContactUs"><i class="fas fa-phone-alt mr-1 text-info"></i>Contact Us</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#AboutUs"><i class="fas fa-chalkboard-teacher mr-1 text-info"></i>About Us</a>
    </li>
}

Views/Shared/_AuthScriptsPartial.cshtml
<script src="~/js/UserRegistration.js" asp-append-version="true"></script>
<script src="~/js/UserLogin.js" asp-append-version="true"></script>
<script src="~/js/BootstrapAlerts.js" asp-append-version="true"></script>

Views/Shared/_DateScriptsPartial.cshtml
<script src="~/js/DateFunctions.js"></script>
<script src="~/js/DatePicker.js"></script>

Views/Shared/_DefaultHomePageContentPartial.cshtml
@model IEnumerable<Programme>
@using SpringOceanTechnologiesIMS.Entities
@using SpringOceanTechnologiesIMS.Models

<!--Hero Section-->
<div class="hero section">
    <img class="img-fluid" src="~/Images/YouthGroup.jpg">
    <div class="hero-heading">
        <h2 class="hero-heading-text">Learn Software Engineering at a <strong>YDC near you!</strong></h2>
        <a id="HeroRegisterButton" class="btn btn-outline-info btn-lg text-light hero-register-button" data-toggle="modal" data-target="#UserRegistrationModal">Register</a>
    </div>
</div>

<hr class="section-divider" />

<!--Courses Section-->
<div id="Courses" class="courses section">
    <h3 class="section-header"><i class="fas fa-laptop-code mr-2 text-info"></i>Courses</h3>
    @{
        const int itemsPerRow = 4;

        var count = Model.Count() / itemsPerRow;
        var progList = new List<Programme>();

    }
    @for (int i = 0; i <= count; i++)
    {
        progList = Model.Skip(i * itemsPerRow).Take(itemsPerRow).ToList();

        <partial name="_DisplayCardRowPartial" model="progList" />

    }
</div>

<hr class="section-divider" />

<!--Contact Us Section-->

<div id="ContactUs" class="contact-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-phone-alt mr-2 text-info"></i>Contact Us</h3>
    <div class="col-md-5">
        Email us any questions or inquiries or call 084 568 4989. We would be happy to answer your questions and set up a meeting with you.
    </div>
    <div class="mt-3">
        <div class="col-md-8">
            <form>
                <input type="hidden" />
                <div class="form-group">
                    <label for="Name" class="control-label">Name: </label>
                    <input id="Name" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Email" class="control-label">Email: </label>
                    <input id="Email" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="Subject" class="control-label">Subject: </label>
                    <input id="Subject" class="form-control" />

                </div>
                <div class="form-group">
                    <label for="MessageBody" class="control-label">Message: </label>
                    <textarea id="Messagebody" cols="30" rows="10" class="form-control"></textarea>

                </div>
                <div class="form-group d-flex">
                    <input type="button" value="Send Email" class="btn btn-outline-info ml-auto" />
                </div>
            </form>
        </div>
    </div>
</div>
<hr class="section-divider" />

<!--About Us Section-->

<div id="AboutUs" class="about-us section">
    <h3 class="col-md-5 section-header"><i class="fas fa-chalkboard-teacher mr-2 text-info"></i>About Us</h3>
    <div class="mt-3 mb-5">
        <div class="col-md-10">
            <p>
                <strong>YDC</strong> The main objective of this assignment is to design, develop and operationalise a web-based MIS system with database application that will assist its users (administrators and global clients) to send,
                access, analyse, process, and convert data into useful information using various search, sort, filter, and rank queries accessible both on local intranet and internet.
                The specific objectives of this assignment are:
                • To develop and establish fully functional computer based MIS covering ECDs, Regional, District and Provincial Department of Social Development information needs.
                • To design and develop web-based /standalone / hand-held mobile database application for online data entry and inquiry.
                • To ensure flexibility in database design to adapt/accept the changes in data that may be required in future management.
            </p>
        </div>
    </div>
</div>

Views/Shared/_DisplayCardRowPartial.cshtml
@using SpringOceanTechnologiesIMS.Entities
@model IEnumerable<Programme>


@if (Model.Count() > 0)
{
    
    <div class="row mt-3">
        @foreach (Programme item in Model)
        {
            <div class="col-md-3 mt-3">
                <a href="#" class="RegisterLink text-dark" data-programmeId="@item.Id">
                    <div class="card">
                        <img class="img-thumbnail" src="@item.ThumbnailImagePath" alt="@item.Title">
                        <div class="card-body">
                            <h5 class="card-title">@item.Title</h5>
                            <p class="card-text">@item.Description</p>
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
    
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpringOceanTechnologiesIMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/fontawesome/css/all.min.css" rel="stylesheet" />
    <link href="~/fontawesome/css/fontawesome.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/SPTLogo.jpg" height="45"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home mr-1 text-info"></i>Home</a>
                        </li>
                        <partial name="_AdminMenuPartial" />
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 main-default">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SpringOceanTechnologiesIMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_UserLoginPartial.cshtml
@model SpringOceanTechnologiesIMS.Models.LoginModel
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="alert_placeholder_login">
                </div>
                <form id="UserLoginForm" asp-controller="UserAuth" asp-action"Login">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="LoginInValid" />
                    <div class="form-group row">
                        <label asp-for="Email" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Email" placeholder="Email Address" class="form-control" />
                           <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Password" class="col-md-4 col-form-label"></label>
                        <div class="col-md-8">
                            <input asp-for="Password" placeholder="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                       <div class="col-md-8 offset-md-4">
                           <div class="form-check">
                               <input asp-for="RememberMe" class="form-check-input" />
                               <label asp-for="RememberMe" class="form-check-label"></label>
                           </div>
                       </div>
                        
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" id="login" name="login" class="btn btn-primary">Login</button>
            </div>
        </div>
    </div>

Views/Shared/_UserRegistrationPartial.cshtml
@model SpringOceanTechnologiesIMS.Models.RegistrationModel
< <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><i class="fas fa-user mr-2 text-info"></i>Register</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="alert_placeholder_register">
            </div>
            <form id="UserRegistrationForm" name="UserRegistrationForm" asp-controller="UserAuth" asp-action="RegisterUser">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="RegistrationInValid">
                <div class="form-group row">
                    <label asp-for="Email" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Email" placeholder="Email Address" class="form-control">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Password" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Password" placeholder="Password" class="form-control">
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="ConfirmPassword" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="ConfirmPassword" placeholder="Confirm Password" class="form-control">
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="FirstName" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="FirstName" placeholder="First Name" class="form-control">
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="LastName" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="LastName" placeholder="Last Name" class="form-control">
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Address1" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Address1" placeholder="Address1" class="form-control">
                        <span asp-validation-for="Address1" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Address2" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="Address2" placeholder="Address2" class="form-control">
                        <span asp-validation-for="Address2" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PostCode" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="PostCode" placeholder="Post Code" class="form-control">
                        <span asp-validation-for="PostCode" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PhoneNumber" class="col-md-4 col-form-label"></label>
                    <div class="col-md-8">
                        <input asp-for="PhoneNumber" placeholder="Phone Number" class="form-control">
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <div class="form-check">
                            <input asp-for="AcceptUserAgreement" class="form-check-input">
                            <label asp-for="AcceptUserAgreement" class="form-check-label">I accept the <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a></label>
                        </div>
                    </div>
                </div>
                <input type="hidden" asp-for="ProgrammeId" />
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button id="register" name="register" type="button" class="btn btn-primary">Register</button>
        </div>
    </div>
</div>