Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SpringOceanTechnologiesIMS.Data;
using SpringOceanTechnologiesIMS.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SpringOceanTechnologiesIMS.Controllers
{
    public class ContentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContentController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int programmeItemId)
        {
            Content content = await (from item in _context.Content
                                     where item.ProgrammeItems.Id == programmeItemId
                                     select new Content
                                     {
                                         Title = item.Title,
                                         VideoLink = item.VideoLink,
                                         HTMLContent = item.HTMLContent
                                     }).FirstOrDefaultAsync();

            return View(content);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SpringOceanTechnologiesIMS.Data;
using SpringOceanTechnologiesIMS.Entities;
using SpringOceanTechnologiesIMS.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SpringOceanTechnologiesIMS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<ProgrammeItemDetailsModel> programmeItemDetailsModels = null;
            IEnumerable<GroupedProgrammeItemsByProgrammeModel> groupedProgrammeItemsByProgrammeModels = null;

            ProgrammeDetailsModel programmeDetailsModel = new ProgrammeDetailsModel();

            if (_signInManager.IsSignedIn(User))
            {
                var user = await _userManager.GetUserAsync(User);

                if (user != null)
                {
                    programmeItemDetailsModels = await GetProgrammeItemDetailsForUser(user.Id);
                    groupedProgrammeItemsByProgrammeModels = GetGroupedProgrammeItemsByProgramme(programmeItemDetailsModels);

                    programmeDetailsModel.GroupedProgrammeItemsByProgrammeModels = groupedProgrammeItemsByProgrammeModels;

                }

            }
            else
            {
                var programmes = await GetProgrammesThatHaveContent();

                programmeDetailsModel.Programmes = programmes;

            }

            return View(programmeDetailsModel);
        }

        private async Task<List<Programme>> GetProgrammesThatHaveContent()
        {
            var programmesWithContent = await (from programme in _context.Programmes
                                              join programmeItem in _context.ProgrammeItems
                                               on programme.Id equals programmeItem.ProgrammeId
                                              join content in _context.Content
                                               on programmeItem.Id equals content.ProgrammeItems.Id
                                               select new Programme
                                               {
                                                   Id = programme.Id,
                                                   Title = programme.Title,
                                                   Description = programme.Description,
                                                   ThumbnailImagePath = programme.ThumbnailImagePath
                                               }).Distinct().ToListAsync();
            return programmesWithContent;

        }

        private IEnumerable<GroupedProgrammeItemsByProgrammeModel> GetGroupedProgrammeItemsByProgramme(IEnumerable<ProgrammeItemDetailsModel> programmeItemDetailsModels)
        {
            return from item in programmeItemDetailsModels
                   group item by item.ProgrammeId into g
                   select new GroupedProgrammeItemsByProgrammeModel
                   {
                       Id = g.Key,
                       Title = g.Select(c => c.ProgrammeTitle).FirstOrDefault(),
                       Items = g
                   };
        }

        private async Task<IEnumerable<ProgrammeItemDetailsModel>> GetProgrammeItemDetailsForUser(string userId)
        {
            return await (from progItem in _context.ProgrammeItems
                          join programme in _context.Programmes
                          on progItem.ProgrammeId equals programme.Id
                          join content in _context.Content
                          on progItem.Id equals content.ProgrammeItems.Id
                          join userProg in _context.UserProgramme
                          on programme.Id equals userProg.ProgrammeId
                          join mediaType in _context.MediaType
                          on progItem.MediaTypeId equals mediaType.Id
                          where userProg.UserId == userId
                          select new ProgrammeItemDetailsModel
                          {
                              ProgrammeId = programme.Id,
                              ProgrammeTitle = programme.Title,
                              ProgrammeItemId = progItem.Id,
                              ProgrammeItemTitle =progItem.Title,
                              ProgrammeItemDescription = progItem.Description,
                              MediaImagePath = mediaType.ThumbnailImagePath
                          }).ToListAsync();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@model ProgrammeDetailsModel
@using Microsoft.AspNetCore.Identity
@using SpringOceanTechnologiesIMS.Data
@inject SignInManager<ApplicationUser> SignInManager;

@{
    ViewData["Title"] = "Home Page";
}


@if (Model.GroupedProgrammeItemsByProgrammeModels != null)
{
    <div class="row">
        <div class="col-md-6">
            <h2>Your Courses</h2>
        </div>
        <div class="col-md-6 text-right">
            <a asp-controller="ProgrammmesToUsers" asp-action="Index" class="btn btn-outline-dark">Choose Courses</a>
        </div>
    </div>

    @if (Model.GroupedProgrammeItemsByProgrammeModels.Count() > 0)
    {

        <div class="row mt-3">
            <div class="col-md-12">

                @foreach (var prog in Model.GroupedProgrammeItemsByProgrammeModels)
                {
                    <div class="card mt-2">
                        <h4 class="card-header text-secondary bg-white" style="cursor:pointer" data-toggle="collapse" data-target="#collapse_@prog.Id" aria-expanded="false" aria-controls="collapse_@prog.Id">
                            @prog.Title
                        </h4>
                        <div id="collapse_@prog.Id" class="collapse" aria-expanded="false" aria-controls="collapse_@prog.Id">
                            <hr />
                            @foreach (var item in prog.Items)
                            {
                                <div class="mt-2">
                                    <img src="@item.MediaImagePath" width="100" height="100" class="img-thumbnail float-left mr-2" />
                                    <h5 class="card-title mt-2">
                                        <a class="text-dark" asp-controller="Content" asp-action="Index" asp-route-ProgrammeItemId="@item.ProgrammeItemId">@item.ProgrammeItemTitle</a>
                                    </h5>
                                    <p class="card-text text-dark mt-2">
                                        @item.ProgrammeItemDescription
                                    </p>
                                </div>
                            }
                        </div>
                    </div>
                }

            </div>
        </div>
    }
    else
    {
        <h4 class="mt-2 text-warning">You are currently not matched with any courses</h4>

    }
}
else
{
    <partial name="_DefaultHomePageContentPartial" model="@Model.Programmes" />
}




<div class="modal fade" id="UserLoginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <partial name="_UserLoginPartial" model="new LoginModel
        {
            Email = String.Empty,
            Password = String.Empty,
            RememberMe = false
        }">
</div>

<div class="modal fade" id="UserRegistrationModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <partial name="_UserRegistrationPartial" model="new RegistrationModel
        {
            Email = String.Empty,
            Password = String.Empty,
            ConfirmPassword = String.Empty,
            FirstName = String.Empty,
            LastName = String.Empty,
            PhoneNumber = String.Empty,
            Address1 = String.Empty,
            Address2 = String.Empty,
            PostCode = String.Empty,
            AcceptUserAgreement = false
        }">
</div>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_AuthScriptsPartial");
        await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }

}